basePath: /
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: Это тестовый сервер Swagger для Gin.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Example API
  version: "1.0"
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: Возвращает сообщение "Hello, World!"
      produces:
      - application/json
      responses:
        "200":
          description: Hello, World!
          schema:
            type: string
      summary: Получить приветствие
      tags:
      - example
swagger: "2.0"
