basePath: /
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: Это тестовый сервер Swagger для Gin.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Example API
  version: "1.0"
paths:
  /api/v1/hello:
    get:
      consumes:
      - application/json
      description: Возвращает сообщение "Hello, World!"
      produces:
      - application/json
      responses:
        "200":
          description: Hello, World!
          schema:
            type: string
      summary: Получить приветствие
      tags:
      - example
  /api/v1/key/{key}:
    get:
      consumes:
      - application/json
      description: Возвращает переданный ключ
      parameters:
      - description: Ключ
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить значение по ключу
      tags:
      - example
  /api/v1/search:
    get:
      consumes:
      - application/json
      description: Возвращает результаты поиска по параметру "q" и отображает выбранную
        страницу через параметр "page"
      parameters:
      - description: Поисковый запрос
        in: query
        name: q
        type: string
      - description: Номер страницы
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Поиск по query-параметрам
      tags:
      - search
swagger: "2.0"
