basePath: /
definitions:
  api.BadRequest:
    properties:
      detail:
        $ref: '#/definitions/api.Message'
    type: object
  api.Message:
    properties:
      message:
        example: Some message
        type: string
      status:
        example: not ok
        type: string
    type: object
  api.UserResponse:
    properties:
      email:
        example: john.doe@example.com
        type: string
      id:
        example: 1
        type: integer
      name:
        example: John Doe
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: Test Swagger for Gin.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Example API
  version: "1.0"
paths:
  /api/v1/create:
    post:
      consumes:
      - application/json
      description: Received json body
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Data from body
      tags:
      - create
  /api/v1/hello:
    get:
      consumes:
      - application/json
      description: Returns "Hello, World!"
      produces:
      - application/json
      responses:
        "200":
          description: Hello, World!
          schema:
            type: string
      tags:
      - example
  /api/v1/key/{key}:
    get:
      consumes:
      - application/json
      description: Return key from path param
      parameters:
      - description: Key
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get key from path param
      tags:
      - example
  /api/v1/search:
    get:
      consumes:
      - application/json
      description: Get "q" and "page" query params
      parameters:
      - description: Search query
        in: query
        name: q
        type: string
      - description: Pagination
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get query params
      tags:
      - search
  /api/v2/users/{id}:
    get:
      consumes:
      - application/json
      description: description
      parameters:
      - description: User id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.BadRequest'
      summary: Endpoint with schema
      tags:
      - with_schema
swagger: "2.0"
