version: "3.9"

services:
  app:
    image: app:latest
    build:
      context: src
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"

  db:
    container_name: db
    build:
       dockerfile: ./docker/postgres/Dockerfile
       context: .
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - src/settings/.env
    ports:
      - '5432:5432'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
       - db
    ports:
      - '5050:80'
    env_file:
      - src/settings/.env

volumes:
  db_volume: